-module(big_switch).
-export([test/0, compile/1]).

test() ->
  fail = long_option_2_p_0(foo),
  ok.

long_option_2_p_0(X) -> 
  case X of
    "Erlang" ->
      erlang ;
    "Erlang-only" ->
      erlang_only ;
    "IL-byref-tailcalls" ->
      il_byref_tailcalls ;
    "IL-funcptr-types" ->
      il_funcptr_types ;
    "IL-only" ->
      il_only ;
    "IL-refany-fields" ->
      il_refany_fields ;
    "Java" ->
      java ;
    "Java-only" ->
      java_only ;
    "agc-stack-layout" ->
      agc_stack_layout ;
    "allow-hijacks" ->
      allow_hijacks ;
    "allow-stubs" ->
      allow_stubs ;
    "allow-undefined" ->
      allow_undefined ;
    "analyse-closures" ->
      analyse_closures ;
    "analyse-exceptions" ->
      analyse_exceptions ;
    "analyse-local-closures" ->
      analyse_closures ;
    "analyse-mm-tabling" ->
      analyse_mm_tabling ;
    "analyse-trail-usage" ->
      analyse_trail_usage ;
    "analysis-repeat" ->
      analysis_repeat ;
    "ansi-c" ->
      ansi_c ;
    "arg-size-analysis-only" ->
      arg_size_analysis_only ;
    "asm-labels" ->
      asm_labels ;
    "assume-gmake" ->
      assume_gmake ;
    "auto-comments" ->
      auto_comments ;
    "automatic-intermodule-optimisation" ->
      automatic_intermodule_optimization ;
    "automatic-intermodule-optimization" ->
      automatic_intermodule_optimization ;
    "backend-foreign-languages" ->
      backend_foreign_languages ;
    "basic-stack-layout" ->
      basic_stack_layout ;
    "benchmark-modes" ->
      benchmark_modes ;
    "benchmark-modes-repeat" ->
      benchmark_modes_repeat ;
    "binary-switch-size" ->
      binary_switch_size ;
    "bits-per-word" ->
      bits_per_word ;
    "body-typeinfo-liveness" ->
      body_typeinfo_liveness ;
    "branch-delay-slot" ->
      have_delay_slot ;
    "bug-foreign_import-2002-08-06" ->
      compiler_sufficiently_recent ;
    "bug-intermod-2002-06-13" ->
      compiler_sufficiently_recent ;
    "bug-intermod-2006-09-28" ->
      compiler_sufficiently_recent ;
    "bytes-per-word" ->
      bytes_per_word ;
    "c-debug" ->
      target_debug ;
    "c-flag-to-name-object-file" ->
      c_flag_to_name_object_file ;
    "c-include-dir" ->
      c_include_directory ;
    "c-include-directory" ->
      c_include_directory ;
    "c-optimise" ->
      c_optimize ;
    "c-optimize" ->
      c_optimize ;
    "can-compare-constants-as-ints" ->
      can_compare_constants_as_ints ;
    "cc" ->
      cc ;
    "cflag" ->
      quoted_cflag ;
    "cflags" ->
      cflags ;
    "cflags-for-ansi" ->
      cflags_for_ansi ;
    "cflags-for-debug" ->
      cflags_for_debug ;
    "cflags-for-gotos" ->
      cflags_for_gotos ;
    "cflags-for-optimization" ->
      cflags_for_optimization ;
    "cflags-for-pic" ->
      cflags_for_pic ;
    "cflags-for-regs" ->
      cflags_for_regs ;
    "cflags-for-threads" ->
      cflags_for_threads ;
    "cflags-for-warnings" ->
      cflags_for_warnings ;
    "check-term" ->
      termination_check ;
    "check-term2" ->
      check_termination2 ;
    "check-termination" ->
      termination_check ;
    "check-termination2" ->
      check_termination2 ;
    "checked-nondet-tailcalls" ->
      checked_nondet_tailcalls ;
    "chk-term" ->
      termination_check ;
    "chk-term2" ->
      check_termination2 ;
    "common-data" ->
      common_data ;
    "common-goal" ->
      common_goal ;
    "common-struct" ->
      common_struct ;
    "compare-specialization" ->
      compare_specialization ;
    "compile-only" ->
      compile_only ;
    "compile-to-C" ->
      compile_to_c ;
    "compile-to-c" ->
      compile_to_c ;
    "compile-to-shared-lib" ->
      compile_to_shared_lib ;
    "conf-low-tag-bits" ->
      conf_low_tag_bits ;
    "config-file" ->
      config_file ;
    "constraint-propagation" ->
      constraint_propagation ;
    "control-granularity" ->
      control_granularity ;
    "convert-to-Mercury" ->
      convert_to_mercury ;
    "convert-to-mercury" ->
      convert_to_mercury ;
    "create-archive-command" ->
      create_archive_command ;
    "create-archive-command-flags" ->
      create_archive_command_flags ;
    "create-archive-command-output-flag" ->
      create_archive_command_output_flag ;
    "cross-compiling" ->
      cross_compiling ;
    "csharp-compiler" ->
      csharp_compiler ;
    "csharp-flag" ->
      quoted_csharp_flag ;
    "csharp-flags" ->
      csharp_flags ;
    "ctgc" ->
      structure_reuse_analysis ;
    "ctgc-constraint" ->
      structure_reuse_constraint ;
    "ctgc-constraint-arg" ->
      structure_reuse_constraint_arg ;
    "debug" ->
      exec_trace ;
    "debug-closure" ->
      debug_closure ;
    "debug-det" ->
      debug_det ;
    "debug-determinism" ->
      debug_det ;
    "debug-il-asm" ->
      debug_il_asm ;
    "debug-intermodule-analysis" ->
      debug_intermodule_analysis ;
    "debug-liveness" ->
      debug_liveness ;
    "debug-make" ->
      debug_make ;
    "debug-mm-tabling-analysis" ->
      debug_mm_tabling_analysis ;
    "debug-mode-constraints" ->
      debug_mode_constraints ;
    "debug-modes" ->
      debug_modes ;
    "debug-modes-minimal" ->
      debug_modes_minimal ;
    "debug-modes-pred-id" ->
      debug_modes_pred_id ;
    "debug-modes-statistics" ->
      debug_modes_statistics ;
    "debug-modes-verbose" ->
      debug_modes_verbose ;
    "debug-opt" ->
      debug_opt ;
    "debug-opt-pred-id" ->
      debug_opt_pred_id ;
    "debug-opt-pred-name" ->
      debug_opt_pred_name ;
    "debug-pd" ->
      debug_pd ;
    "debug-stack-opt" ->
      debug_stack_opt ;
    "debug-term" ->
      debug_term ;
    "debug-termination" ->
      debug_term ;
    "debug-trail-usage" ->
      debug_trail_usage ;
    "debug-types" ->
      debug_types ;
    "decl-debug" ->
      decl_debug ;
    "deep-profile-tail-recursion" ->
      deep_profile_tail_recursion ;
    "deep-profiling" ->
      deep_profiling ;
    "deforestation" ->
      deforestation ;
    "deforestation-cost-factor" ->
      deforestation_cost_factor ;
    "deforestation-depth-limit" ->
      deforestation_depth_limit ;
    "deforestation-size-threshold" ->
      deforestation_size_threshold ;
    "deforestation-vars-threshold" ->
      deforestation_vars_threshold ;
    "delay-construct" ->
      delay_construct ;
    "delay-constructs" ->
      delay_construct ;
    "delay-death" ->
      delay_death ;
    "delay-partial-instantiations" ->
      delay_partial_instantiations ;
    "demangle" ->
      demangle ;
    "demangle-command" ->
      demangle_command ;
    "dense-switch-req-density" ->
      dense_switch_req_density ;
    "dense-switch-size" ->
      dense_switch_size ;
    "det-copy-out" ->
      det_copy_out ;
    "detailed-statistics" ->
      detailed_statistics ;
    "disable-mm-cut" ->
      disable_minimal_model_stack_copy_cut ;
    "disable-mm-pneg" ->
      disable_minimal_model_stack_copy_pneg ;
    "disable-trail-ops" ->
      disable_trail_ops ;
    "distance-granularity" ->
      distance_granularity ;
    "dotnet-library-version" ->
      dotnet_library_version ;
    "dump-hlds" ->
      dump_hlds ;
    "dump-hlds-alias" ->
      dump_hlds_alias ;
    "dump-hlds-file-suffix" ->
      dump_hlds_file_suffix ;
    "dump-hlds-options" ->
      dump_hlds_options ;
    "dump-hlds-pred-id" ->
      dump_hlds_pred_id ;
    "dump-mlds" ->
      dump_mlds ;
    "dump-trace-counts" ->
      dump_trace_counts ;
    "eliminate-local-vars" ->
      eliminate_local_vars ;
    "emit-c-loops" ->
      emit_c_loops ;
    "enable-term" ->
      termination ;
    "enable-term2" ->
      termination2 ;
    "enable-termination" ->
      termination ;
    "enable-termination2" ->
      termination2 ;
    "erlang" ->
      erlang ;
    "erlang-compiler" ->
      erlang_compiler ;
    "erlang-flag" ->
      quoted_erlang_flag ;
    "erlang-flags" ->
      erlang_flags ;
    "erlang-object-file-extension" ->
      erlang_object_file_extension ;
    "erlang-only" ->
      erlang_only ;
    "errorcheck-only" ->
      errorcheck_only ;
    "event-set-file-name" ->
      event_set_file_name ;
    "everything-in-one-C-function" ->
      everything_in_one_c_function ;
    "everything-in-one-c-function" ->
      everything_in_one_c_function ;
    "excess-assign" ->
      excess_assign ;
    "executable-file-extension" ->
      executable_file_extension ;
    "experiment" ->
      experiment ;
    "experimental-complexity" ->
      experimental_complexity ;
    "extend-stacks-when-needed" ->
      extend_stacks_when_needed ;
    "extra-init-command" ->
      extra_init_command ;
    "extra-initialization-functions" ->
      extra_initialization_functions ;
    "extra-inits" ->
      extra_initialization_functions ;
    "fact-table-hash-percent-full" ->
      fact_table_hash_percent_full ;
    "fact-table-max-array-size" ->
      fact_table_max_array_size ;
    "feedback-file" ->
      feedback_file ;
    "filenames-from-stdin" ->
      filenames_from_stdin ;
    "find-all-recompilation-reasons" ->
      find_all_recompilation_reasons ;
    "fixed-user-guided-type-specialization" ->
      user_guided_type_specialization ;
    "flags" ->
      flags_file ;
    "flags-file" ->
      flags_file ;
    "follow-code" ->
      follow_code ;
    "force-disable-tracing" ->
      force_disable_tracing ;
    "frameopt-comments" ->
      frameopt_comments ;
    "fullarch" ->
      fullarch ;
    "fully-strict" ->
      fully_strict ;
    "garbage-collection" ->
      gc ;
    "gc" ->
      gc ;
    "gcc-global-registers" ->
      gcc_global_registers ;
    "gcc-local-labels" ->
      gcc_local_labels ;
    "gcc-nested-functions" ->
      gcc_nested_functions ;
    "gcc-non-local-gotos" ->
      gcc_non_local_gotos ;
    "generate-bytecode" ->
      generate_bytecode ;
    "generate-dependencies" ->
      generate_dependencies ;
    "generate-dependency-file" ->
      generate_dependency_file ;
    "generate-mmc-deps" ->
      generate_mmc_make_module_dependencies ;
    "generate-mmc-make-module-dependencies" ->
      generate_mmc_make_module_dependencies ;
    "generate-module-order" ->
      generate_module_order ;
    "generate-source-file-mapping" ->
      generate_source_file_mapping ;
    "generate-standalone-interface" ->
      generate_standalone_interface ;
    "generate-trail-ops-inline" ->
      generate_trail_ops_inline ;
    "grade" ->
      grade ;
    "halt-at-syntax-errors" ->
      halt_at_syntax_errors ;
    "halt-at-warn" ->
      halt_at_warn ;
    "have-delay-slot" ->
      have_delay_slot ;
    "help" ->
      help ;
    "high-level-C" ->
      highlevel_code ;
    "high-level-c" ->
      highlevel_code ;
    "high-level-code" ->
      highlevel_code ;
    "high-level-data" ->
      highlevel_data ;
    "higher-order-arg-limit" ->
      higher_order_arg_limit ;
    "higher-order-size-limit" ->
      higher_order_size_limit ;
    "highlevel-C" ->
      highlevel_code ;
    "highlevel-c" ->
      highlevel_code ;
    "highlevel-code" ->
      highlevel_code ;
    "highlevel-data" ->
      highlevel_data ;
    "hlds-dump" ->
      dump_hlds ;
    "il" ->
      il ;
    "il-assembler" ->
      il_assembler ;
    "il-byref-tailcalls" ->
      il_byref_tailcalls ;
    "il-funcptr-types" ->
      il_funcptr_types ;
    "il-only" ->
      il_only ;
    "il-refany-fields" ->
      il_refany_fields ;
    "ilasm-flag" ->
      quoted_ilasm_flag ;
    "ilasm-flags" ->
      ilasm_flags ;
    "implicit-parallelism" ->
      implicit_parallelism ;
    "imports-graph" ->
      imports_graph ;
    "infer-all" ->
      infer_all ;
    "infer-det" ->
      infer_det ;
    "infer-determinism" ->
      infer_det ;
    "infer-modes" ->
      infer_modes ;
    "infer-types" ->
      infer_types ;
    "inhibit-accumulator-warnings" ->
      inhibit_accumulator_warnings ;
    "inhibit-warnings" ->
      inhibit_warnings ;
    "init-file" ->
      init_files ;
    "init-file-directory" ->
      init_file_directories ;
    "inline-alloc" ->
      inline_alloc ;
    "inline-builtins" ->
      inline_builtins ;
    "inline-call-cost" ->
      inline_call_cost ;
    "inline-compound-threshold" ->
      inline_compound_threshold ;
    "inline-simple" ->
      inline_simple ;
    "inline-simple-threshold" ->
      inline_simple_threshold ;
    "inline-single-use" ->
      inline_single_use ;
    "inline-vars-threshold" ->
      inline_vars_threshold ;
    "inlining" ->
      inlining ;
    "install-command" ->
      install_command ;
    "install-command-dir-option" ->
      install_command_dir_option ;
    "install-opt-files-2002-08-30" ->
      compiler_sufficiently_recent ;
    "install-prefix" ->
      install_prefix ;
    "intermod-directory" ->
      intermod_directories ;
    "intermod-inline-simple-threshold" ->
      intermod_inline_simple_threshold ;
    "intermod-opt" ->
      intermodule_optimization ;
    "intermod-unused-args" ->
      intermod_unused_args ;
    "intermodule-analysis" ->
      intermodule_analysis ;
    "intermodule-optimisation" ->
      intermodule_optimization ;
    "intermodule-optimization" ->
      intermodule_optimization ;
    "introduce-accumulators" ->
      introduce_accumulators ;
    "invoked-by-mmc-make" ->
      invoked_by_mmc_make ;
    "java" ->
      java ;
    "java-classpath" ->
      java_classpath ;
    "java-compiler" ->
      java_compiler ;
    "java-debug" ->
      target_debug ;
    "java-flag" ->
      quoted_java_flag ;
    "java-flags" ->
      java_flags ;
    "java-interpreter" ->
      java_interpreter ;
    "java-object-file-extension" ->
      java_object_file_extension ;
    "java-only" ->
      java_only ;
    "javac" ->
      java_compiler ;
    "jobs" ->
      jobs ;
    "keep-going" ->
      keep_going ;
    "ld-flag" ->
      quoted_ld_flag ;
    "ld-flags" ->
      ld_flags ;
    "ld-libflag" ->
      quoted_ld_libflag ;
    "ld-libflags" ->
      ld_libflags ;
    "lib-linkage" ->
      lib_linkages ;
    "libgrade" ->
      libgrades ;
    "library" ->
      link_libraries ;
    "library-directory" ->
      link_library_directories ;
    "library-extension" ->
      library_extension ;
    "library-grade" ->
      libgrades ;
    "library-linkage" ->
      lib_linkages ;
    "line-numbers" ->
      line_numbers ;
    "link-executable-command" ->
      link_executable_command ;
    "link-object" ->
      link_objects ;
    "link-shared-lib-command" ->
      link_shared_lib_command ;
    "link-with-pic-object-file-extension" ->
      link_with_pic_object_file_extension ;
    "linkage" ->
      linkage_special ;
    "linker-allow-undefined-flag" ->
      linker_allow_undefined_flag ;
    "linker-debug-flags" ->
      linker_debug_flags ;
    "linker-error-undefined-flag" ->
      linker_error_undefined_flag ;
    "linker-link-lib-flag" ->
      linker_link_lib_flag ;
    "linker-link-lib-suffix" ->
      linker_link_lib_suffix ;
    "linker-opt-separator" ->
      linker_opt_separator ;
    "linker-path-flag" ->
      linker_path_flag ;
    "linker-rpath-flag" ->
      linker_rpath_flag ;
    "linker-rpath-separator" ->
      linker_rpath_separator ;
    "linker-static-flags" ->
      linker_static_flags ;
    "linker-strip-flag" ->
      linker_strip_flag ;
    "linker-thread-flags" ->
      linker_thread_flags ;
    "linker-trace-flags" ->
      linker_trace_flags ;
    "llds-optimise" ->
      optimize ;
    "llds-optimize" ->
      optimize ;
    "local-constraint-propagation" ->
      local_constraint_propagation ;
    "local-module-id" ->
      local_module_id ;
    "local-thread-engine-base" ->
      local_thread_engine_base ;
    "local-var-access-threshold" ->
      local_var_access_threshold ;
    "lookup-switch-req-density" ->
      lookup_switch_req_density ;
    "lookup-switch-size" ->
      lookup_switch_size ;
    "loop-invariants" ->
      loop_invariants ;
    "low-level-debug" ->
      low_level_debug ;
    "main" ->
      main ;
    "make" ->
      make ;
    "make-analysis-registry" ->
      make_analysis_registry ;
    "make-int" ->
      make_interface ;
    "make-interface" ->
      make_interface ;
    "make-opt-int" ->
      make_optimization_interface ;
    "make-optimisation-interface" ->
      make_optimization_interface ;
    "make-optimization-interface" ->
      make_optimization_interface ;
    "make-priv-int" ->
      make_private_interface ;
    "make-private-interface" ->
      make_private_interface ;
    "make-short-int" ->
      make_short_interface ;
    "make-short-interface" ->
      make_short_interface ;
    "make-trans-opt" ->
      make_transitive_opt_interface ;
    "make-transitive-optimisation-interface" ->
      make_transitive_opt_interface ;
    "make-transitive-optimization-interface" ->
      make_transitive_opt_interface ;
    "make-xml-doc" ->
      make_xml_documentation ;
    "make-xml-documentation" ->
      make_xml_documentation ;
    "math-lib" ->
      math_lib ;
    "max-jump-table-size" ->
      max_jump_table_size ;
    "maybe-thread-safe" ->
      maybe_thread_safe_opt ;
    "mcpp-compiler" ->
      mcpp_compiler ;
    "mcpp-flag" ->
      quoted_mcpp_flag ;
    "mcpp-flags" ->
      mcpp_flags ;
    "memory-profiling" ->
      memory_profiling ;
    "mercury-config-dir" ->
      mercury_configuration_directory_special ;
    "mercury-configuration-directory" ->
      mercury_configuration_directory_special ;
    "mercury-library" ->
      mercury_library_special ;
    "mercury-library-directory" ->
      mercury_library_directory_special ;
    "mercury-linkage" ->
      mercury_linkage_special ;
    "mercury-standard-library-directory" ->
      mercury_standard_library_directory_special ;
    "mercury-stdlib-dir" ->
      mercury_standard_library_directory_special ;
    "middle-rec" ->
      middle_rec ;
    "minimal-model-debug" ->
      minimal_model_debug ;
    "mkinit-command" ->
      mkinit_command ;
    "mkinit-erl-command" ->
      mkinit_erl_command ;
    "ml" ->
      mercury_library_special ;
    "mld" ->
      mercury_library_directory_special ;
    "mlds-dump" ->
      dump_mlds ;
    "mlds-optimise" ->
      optimize ;
    "mlds-optimize" ->
      optimize ;
    "mode-constraints" ->
      mode_constraints ;
    "mode-inference-iteration-limit" ->
      mode_inference_iteration_limit ;
    "mutable-always-boxed" ->
      mutable_always_boxed ;
    "new-type-class-rtti" ->
      new_type_class_rtti ;
    "no-noncompact-ho-call-2004-01-15" ->
      compiler_sufficiently_recent ;
    "nondet-copy-out" ->
      nondet_copy_out ;
    "num-real-f-regs" ->
      num_real_f_regs ;
    "num-real-f-temps" ->
      num_real_f_temps ;
    "num-real-r-regs" ->
      num_real_r_regs ;
    "num-real-r-temps" ->
      num_real_r_temps ;
    "num-real-temps" ->
      num_real_r_temps ;
    "num-reserved-addresses" ->
      num_reserved_addresses ;
    "num-reserved-objects" ->
      num_reserved_objects ;
    "num-tag-bits" ->
      num_tag_bits ;
    "object-file-extension" ->
      object_file_extension ;
    "opt-level" ->
      opt_level ;
    "opt-no-return-calls" ->
      opt_no_return_calls ;
    "opt-space" ->
      opt_space ;
    "optimisation-level" ->
      opt_level ;
    "optimise-constant-propagation" ->
      constant_propagation ;
    "optimise-constructor-last-call" ->
      optimize_constructor_last_call ;
    "optimise-constructor-last-call-accumulator" ->
      optimize_constructor_last_call_accumulator ;
    "optimise-constructor-last-call-null" ->
      optimize_constructor_last_call_null ;
    "optimise-dead-procs" ->
      optimize_dead_procs ;
    "optimise-delay-slot" ->
      optimize_delay_slot ;
    "optimise-duplicate-calls" ->
      optimize_duplicate_calls ;
    "optimise-dups" ->
      optimize_dups ;
    "optimise-frames" ->
      optimize_frames ;
    "optimise-fulljumps" ->
      optimize_fulljumps ;
    "optimise-higher-order" ->
      optimize_higher_order ;
    "optimise-initializations" ->
      optimize_initializations ;
    "optimise-jumps" ->
      optimize_jumps ;
    "optimise-labels" ->
      optimize_labels ;
    "optimise-peep" ->
      optimize_peep ;
    "optimise-proc-dups" ->
      optimize_proc_dups ;
    "optimise-reassign" ->
      optimize_reassign ;
    "optimise-repeat" ->
      optimize_repeat ;
    "optimise-saved-vars" ->
      optimize_saved_vars ;
    "optimise-saved-vars-cell" ->
      optimize_saved_vars_cell ;
    "optimise-saved-vars-const" ->
      optimize_saved_vars_const ;
    "optimise-space" ->
      opt_space ;
    "optimise-tailcalls" ->
      optimize_tailcalls ;
    "optimise-unused-args" ->
      optimize_unused_args ;
    "optimization-level" ->
      opt_level ;
    "optimize-constant-propagation" ->
      constant_propagation ;
    "optimize-constructor-last-call" ->
      optimize_constructor_last_call ;
    "optimize-constructor-last-call-accumulator" ->
      optimize_constructor_last_call_accumulator ;
    "optimize-constructor-last-call-null" ->
      optimize_constructor_last_call_null ;
    "optimize-dead-procs" ->
      optimize_dead_procs ;
    "optimize-delay-slot" ->
      optimize_delay_slot ;
    "optimize-duplicate-calls" ->
      optimize_duplicate_calls ;
    "optimize-dups" ->
      optimize_dups ;
    "optimize-frames" ->
      optimize_frames ;
    "optimize-fulljumps" ->
      optimize_fulljumps ;
    "optimize-higher-order" ->
      optimize_higher_order ;
    "optimize-initializations" ->
      optimize_initializations ;
    "optimize-jumps" ->
      optimize_jumps ;
    "optimize-labels" ->
      optimize_labels ;
    "optimize-peep" ->
      optimize_peep ;
    "optimize-proc-dups" ->
      optimize_proc_dups ;
    "optimize-reassign" ->
      optimize_reassign ;
    "optimize-repeat" ->
      optimize_repeat ;
    "optimize-saved-vars" ->
      optimize_saved_vars ;
    "optimize-saved-vars-cell" ->
      optimize_saved_vars_cell ;
    "optimize-saved-vars-const" ->
      optimize_saved_vars_const ;
    "optimize-space" ->
      opt_space ;
    "optimize-tailcalls" ->
      optimize_tailcalls ;
    "optimize-trail-usage" ->
      optimize_trail_usage ;
    "optimize-unused-args" ->
      optimize_unused_args ;
    "options-file" ->
      options_files ;
    "options-search-directory" ->
      options_search_directories ;
    "osv-all-cand" ->
      optimize_saved_vars_cell_include_all_candidates ;
    "osv-allpath-node-ratio" ->
      optimize_saved_vars_cell_all_path_node_ratio ;
    "osv-cand-head" ->
      optimize_saved_vars_cell_candidate_headvars ;
    "osv-cvload-cost" ->
      optimize_saved_vars_cell_cv_load_cost ;
    "osv-cvstore-cost" ->
      optimize_saved_vars_cell_cv_store_cost ;
    "osv-full-path" ->
      optimize_saved_vars_cell_full_path ;
    "osv-fvload-cost" ->
      optimize_saved_vars_cell_fv_load_cost ;
    "osv-fvstore-cost" ->
      optimize_saved_vars_cell_fv_store_cost ;
    "osv-loop" ->
      optimize_saved_vars_cell_loop ;
    "osv-node-ratio" ->
      optimize_saved_vars_cell_node_ratio ;
    "osv-on-stack" ->
      optimize_saved_vars_cell_on_stack ;
    "osv-op-ratio" ->
      optimize_saved_vars_cell_op_ratio ;
    "output-cc" ->
      output_cc ;
    "output-compile-error-lines" ->
      output_compile_error_lines ;
    "output-file" ->
      output_file_name ;
    "output-grade-string" ->
      output_grade_string ;
    "output-libgrades" ->
      output_libgrades ;
    "output-link-command" ->
      output_link_command ;
    "output-shared-lib-link-command" ->
      output_shared_lib_link_command ;
    "parallel" ->
      parallel ;
    "parallel-code-gen" ->
      parallel_code_gen ;
    "parallel-liveness" ->
      parallel_liveness ;
    "parallelism-target" ->
      parallelism_target ;
    "pessimize-tailcalls" ->
      pessimize_tailcalls ;
    "pic" ->
      pic ;
    "pic-object-file-extension" ->
      pic_object_file_extension ;
    "pic-reg" ->
      pic_reg ;
    "polymorphism" ->
      polymorphism ;
    "pre-link-command" ->
      pre_link_command ;
    "prefer-switch" ->
      prefer_switch ;
    "pretty-print" ->
      convert_to_mercury ;
    "procid-stack-layout" ->
      procid_stack_layout ;
    "procs-per-C-function" ->
      procs_per_c_function ;
    "procs-per-c-function" ->
      procs_per_c_function ;
    "profile-calls" ->
      profile_calls ;
    "profile-deep" ->
      profile_deep ;
    "profile-memory" ->
      profile_memory ;
    "profile-optimised" ->
      prof_optimized ;
    "profile-optimized" ->
      prof_optimized ;
    "profile-time" ->
      profile_time ;
    "profiling" ->
      profiling ;
    "prop-mode-constraints" ->
      prop_mode_constraints ;
    "propagate-mode-constraints" ->
      prop_mode_constraints ;
    "put-commit-in-own-func" ->
      put_commit_in_own_func ;
    "put-nondet-env-on-heap" ->
      put_nondet_env_on_heap ;
    "ranlib-command" ->
      ranlib_command ;
    "ranlib-flags" ->
      ranlib_flags ;
    "read-config-file-2003-03-01" ->
      compiler_sufficiently_recent ;
    "read-opt-files-transitively" ->
      read_opt_files_transitively ;
    "readline-libs" ->
      readline_libs ;
    "rebuild" ->
      rebuild ;
    "reclaim-heap-on-failure" ->
      reclaim_heap_on_failure ;
    "reclaim-heap-on-nondet-failure" ->
      reclaim_heap_on_nondet_failure ;
    "reclaim-heap-on-semidet-failure" ->
      reclaim_heap_on_semidet_failure ;
    "record-term-sizes-as-cells" ->
      record_term_sizes_as_cells ;
    "record-term-sizes-as-words" ->
      record_term_sizes_as_words ;
    "region-analysis" ->
      region_analysis ;
    "reorder-conj" ->
      reorder_conj ;
    "reorder-disj" ->
      reorder_disj ;
    "reserve-tag" ->
      reserve_tag ;
    "rtti-line-numbers" ->
      rtti_line_numbers ;
    "runtime-flags" ->
      runtime_flags ;
    "runtime-library-directory" ->
      runtime_link_library_directories ;
    "search-directory" ->
      search_directories ;
    "search-lib-files-dir" ->
      search_library_files_directory_special ;
    "search-library-files-directory" ->
      search_library_files_directory_special ;
    "separate-assemblies" ->
      separate_assemblies ;
    "shared-library-extension" ->
      shared_library_extension ;
    "shared-libs" ->
      shared_libs ;
    "shlib-linker-debug-flags" ->
      shlib_linker_debug_flags ;
    "shlib-linker-install-name-flag" ->
      shlib_linker_install_name_flag ;
    "shlib-linker-install-name-path" ->
      shlib_linker_install_name_path ;
    "shlib-linker-link-lib-flag" ->
      shlib_linker_link_lib_flag ;
    "shlib-linker-link-lib-suffix" ->
      shlib_linker_link_lib_suffix ;
    "shlib-linker-rpath-flag" ->
      shlib_linker_rpath_flag ;
    "shlib-linker-rpath-separator" ->
      shlib_linker_rpath_separator ;
    "shlib-linker-thread-flags" ->
      shlib_linker_thread_flags ;
    "shlib-linker-trace-flags" ->
      shlib_linker_trace_flags ;
    "shlib-linker-use-install-name" ->
      shlib_linker_use_install_name ;
    "should-pretest-equality" ->
      should_pretest_equality ;
    "show-dependency-graph" ->
      show_dependency_graph ;
    "sign-assembly" ->
      sign_assembly ;
    "simple-mode-constraints" ->
      simple_mode_constraints ;
    "simple-neg" ->
      simple_neg ;
    "single-prec-float" ->
      single_prec_float ;
    "single-precision-float" ->
      single_prec_float ;
    "smart-indexing" ->
      smart_indexing ;
    "smart-recompilation" ->
      smart_recompilation ;
    "special-preds" ->
      special_preds ;
    "stack-segments" ->
      stack_segments ;
    "stack-trace-higher-order" ->
      stack_trace_higher_order ;
    "standardise-labels" ->
      standardize_labels ;
    "standardize-labels" ->
      standardize_labels ;
    "static-ground-terms" ->
      static_ground_terms ;
    "statistics" ->
      statistics ;
    "strict-sequential" ->
      strict_sequential ;
    "string-switch-size" ->
      string_switch_size ;
    "strip" ->
      strip ;
    "structure-reuse" ->
      structure_reuse_analysis ;
    "structure-reuse-constraint" ->
      structure_reuse_constraint ;
    "structure-reuse-constraint-arg" ->
      structure_reuse_constraint_arg ;
    "structure-sharing" ->
      structure_sharing_analysis ;
    "structure-sharing-widening" ->
      structure_sharing_widening ;
    "support-ms-clr" ->
      support_ms_clr ;
    "support-rotor-clr" ->
      support_rotor_clr ;
    "suppress-trace" ->
      suppress_trace ;
    "sync-term-size" ->
      sync_term_size ;
    "table-debug" ->
      table_debug ;
    "tag-switch-size" ->
      tag_switch_size ;
    "tags" ->
      tags ;
    "target" ->
      target ;
    "target-code-only" ->
      target_code_only ;
    "target-debug" ->
      target_debug ;
    "term-err-limit" ->
      termination_error_limit ;
    "term-norm" ->
      termination_norm ;
    "term-path-limit" ->
      termination_path_limit ;
    "term-single-arg" ->
      termination_single_args ;
    "term2-max-matrix-size" ->
      term2_maximum_matrix_size ;
    "term2-norm" ->
      termination2_norm ;
    "term2-propagate-failure-constraints" ->
      propagate_failure_constrs ;
    "term2-propagate-failure-constrs" ->
      propagate_failure_constrs ;
    "term2-widening-limit" ->
      widening_limit ;
    "termination-error-limit" ->
      termination_error_limit ;
    "termination-norm" ->
      termination_norm ;
    "termination-path-limit" ->
      termination_path_limit ;
    "termination-single-argument-analysis" ->
      termination_single_args ;
    "termination2-maximum-matrix-size" ->
      term2_maximum_matrix_size ;
    "termination2-norm" ->
      termination2_norm ;
    "termination2-propagate-failure-constraints" ->
      propagate_failure_constrs ;
    "termination2-widening-limit" ->
      widening_limit ;
    "thread-libs" ->
      thread_libs ;
    "time-profiling" ->
      time_profiling ;
    "trace" ->
      trace_level ;
    "trace-flag" ->
      trace_goal_flags ;
    "trace-init-file" ->
      trace_init_files ;
    "trace-io-builtins-2006-08-14" ->
      compiler_sufficiently_recent ;
    "trace-libs" ->
      trace_libs ;
    "trace-optimised" ->
      trace_optimized ;
    "trace-optimized" ->
      trace_optimized ;
    "trace-prof" ->
      trace_prof ;
    "trace-stack-layout" ->
      trace_stack_layout ;
    "trace-table-io" ->
      trace_table_io ;
    "trace-table-io-all" ->
      trace_table_io_all ;
    "trace-table-io-only-retry" ->
      trace_table_io_only_retry ;
    "trace-table-io-require" ->
      trace_table_io_require ;
    "trace-table-io-states" ->
      trace_table_io_states ;
    "trad-passes" ->
      trad_passes ;
    "trans-intermod-opt" ->
      transitive_optimization ;
    "transitive-intermodule-optimisation" ->
      transitive_optimization ;
    "transitive-intermodule-optimization" ->
      transitive_optimization ;
    "try-switch-size" ->
      try_switch_size ;
    "tuple" ->
      tuple ;
    "tuple-costs-ratio" ->
      tuple_costs_ratio ;
    "tuple-min-args" ->
      tuple_min_args ;
    "tuple-trace-counts-file" ->
      tuple_trace_counts_file ;
    "type-ctor-functors" ->
      type_ctor_functors ;
    "type-ctor-info" ->
      type_ctor_info ;
    "type-ctor-layout" ->
      type_ctor_layout ;
    "type-inference-iteration-limit" ->
      type_inference_iteration_limit ;
    "type-layout" ->
      type_layout ;
    "type-specialisation" ->
      type_specialization ;
    "type-specialization" ->
      type_specialization ;
    "typecheck-ambiguity-error-limit" ->
      typecheck_ambiguity_error_limit ;
    "typecheck-ambiguity-warn-limit" ->
      typecheck_ambiguity_warn_limit ;
    "typecheck-only" ->
      typecheck_only ;
    "unboxed-enums" ->
      unboxed_enums ;
    "unboxed-float" ->
      unboxed_float ;
    "unboxed-no-tag-types" ->
      unboxed_no_tag_types ;
    "unneeded-code" ->
      unneeded_code ;
    "unneeded-code-copy-limit" ->
      unneeded_code_copy_limit ;
    "untuple" ->
      untuple ;
    "use-activation-counts" ->
      use_activation_counts ;
    "use-atomic-cells" ->
      use_atomic_cells ;
    "use-grade-subdirs" ->
      use_grade_subdirs ;
    "use-local-vars" ->
      use_local_vars ;
    "use-lots-of-ho-specialization" ->
      use_lots_of_ho_specialization ;
    "use-macro-for-redo-fail" ->
      use_macro_for_redo_fail ;
    "use-minimal-model-own-stacks" ->
      use_minimal_model_own_stacks ;
    "use-minimal-model-stack_copy" ->
      use_minimal_model_stack_copy ;
    "use-opt-files" ->
      use_opt_files ;
    "use-readline" ->
      use_readline ;
    "use-regions" ->
      use_regions ;
    "use-search-directories-for-intermod" ->
      use_search_directories_for_intermod ;
    "use-subdirs" ->
      use_subdirs ;
    "use-symlinks" ->
      use_symlinks ;
    "use-trail" ->
      use_trail ;
    "use-trans-opt-files" ->
      use_trans_opt_files ;
    "use-zeroing-for-ho-cycles" ->
      use_zeroing_for_ho_cycles ;
    "user-guided-type-specialisation" ->
      user_guided_type_specialization ;
    "user-guided-type-specialization" ->
      user_guided_type_specialization ;
    "verb-check-term" ->
      verbose_check_termination ;
    "verb-check-term2" ->
      verbose_check_termination2 ;
    "verb-chk-term" ->
      verbose_check_termination ;
    "verb-chk-term2" ->
      verbose_check_termination2 ;
    "verbose" ->
      verbose ;
    "verbose-check-termination" ->
      verbose_check_termination ;
    "verbose-check-termination2" ->
      verbose_check_termination2 ;
    "verbose-commands" ->
      verbose_commands ;
    "verbose-dump-mlds" ->
      verbose_dump_mlds ;
    "verbose-error-messages" ->
      verbose_errors ;
    "verbose-make" ->
      verbose_make ;
    "verbose-mlds-dump" ->
      verbose_dump_mlds ;
    "verbose-recompilation" ->
      verbose_recompilation ;
    "verifiable" ->
      verifiable_code ;
    "verifiable-code" ->
      verifiable_code ;
    "version" ->
      version ;
    "very-verbose" ->
      very_verbose ;
    "warn-dead-procs" ->
      warn_dead_procs ;
    "warn-det-decls-too-lax" ->
      warn_det_decls_too_lax ;
    "warn-duplicate-calls" ->
      warn_duplicate_calls ;
    "warn-inferred-erroneous" ->
      warn_inferred_erroneous ;
    "warn-insts-without-matching-type" ->
      warn_insts_without_matching_type ;
    "warn-interface-imports" ->
      warn_interface_imports ;
    "warn-known-bad-format-calls" ->
      warn_known_bad_format_calls ;
    "warn-missing-module-name" ->
      warn_missing_module_name ;
    "warn-missing-opt-files" ->
      warn_missing_opt_files ;
    "warn-missing-trans-opt-deps" ->
      warn_missing_trans_opt_deps ;
    "warn-missing-trans-opt-files" ->
      warn_missing_trans_opt_files ;
    "warn-non-stratification" ->
      warn_non_stratification ;
    "warn-non-tail-recursion" ->
      warn_non_tail_recursion ;
    "warn-non-term-special-preds" ->
      warn_non_term_special_preds ;
    "warn-nothing-exported" ->
      warn_nothing_exported ;
    "warn-obsolete" ->
      warn_obsolete ;
    "warn-overlapping-scopes" ->
      warn_overlapping_scopes ;
    "warn-simple-code" ->
      warn_simple_code ;
    "warn-singleton-variables" ->
      warn_singleton_vars ;
    "warn-smart-recompilation" ->
      warn_smart_recompilation ;
    "warn-stubs" ->
      warn_stubs ;
    "warn-table-with-inline" ->
      warn_table_with_inline ;
    "warn-target-code" ->
      warn_target_code ;
    "warn-undefined-options-variables" ->
      warn_undefined_options_variables ;
    "warn-unification-cannot-succeed" ->
      warn_unification_cannot_succeed ;
    "warn-unknown-format-calls" ->
      warn_unknown_format_calls ;
    "warn-unused-args" ->
      warn_unused_args ;
    "warn-unused-imports" ->
      warn_unused_imports ;
    "warn-up-to-date" ->
      warn_up_to_date ;
    "warn-wrong-module-name" ->
      warn_wrong_module_name ;
    "x86-64" ->
      x86_64 ;
    "x86-64-only" ->
      x86_64_only ;
    "x86_64" ->
      x86_64 ;
    "x86_64-only" ->
      x86_64_only ;
    _ ->
      fail 
  end.

compile(Opts) ->
  hipe:c(?MODULE, Opts).

